version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./event_horizon/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /sslcerts/fullchain.pem:/etc/nginx/dns-cert.pem
      - /sslcerts/privkey.pem:/etc/nginx/dns-cert-key.pem
  restful-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./event_horizon/restful-api
    volumes:
      - /app/node_modules
      - ./event_horizon/restful-api:/app
    environment:
      - EH_MONGO_PATH=${EH_MONGO_PATH} 
      - EH_MONGO_DEFAULT_DB=${EH_MONGO_DEFAULT_DB}
      - EH_MONGO_REPLICA_SET_NAME=${EH_MONGO_REPLICA_SET_NAME}
      - EH_MASTER_TOKEN=${EH_MASTER_TOKEN}
      - EH_SEND_GRID_TOKEN=${EH_SEND_GRID_TOKEN}
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  portal:
    build:
      dockerfile: Dockerfile
      context: ./projects/main/
    volumes:
      - /app/node_modules
      - ./projects/main:/app
  asset_daemon:
    build:
      dockerfile: dockerfile-asset_daemon
      context: ./event_horizon/native
    container_name: "asset-daemon-dev"
    restart: always
    ports:
      - "27017:27017"
    environment:
      - EH_MONGO_PATH=${EH_MONGO_PATH} 
      - EH_MONGO_DEFAULT_DB=${EH_MONGO_DEFAULT_DB}
      - EH_MONGO_REPLICA_SET_NAME=${EH_MONGO_REPLICA_SET_NAME}
    depends_on:
      - rsinitiate      
  mongo1:
    image: "mongo"
    container_name: "mongodb_container1"
    restart: always
    volumes:
      - ${MTN_DB_PATH}/dbc:/data/db
    expose:
      - 27017
    ports:
      - "27011:27017"
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  mongo2:
    image: "mongo"
    container_name: "mongodb_container2"
    restart: always
    expose:
      - 27017
    volumes:
      - ${MTN_DB_PATH}/dbc2:/data/db
    ports:
      - "27012:27017"
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  mongo3:
    image: "mongo"
    container_name: "mongodb_container3"
    restart: always
    expose:
      - 27017
    ports:
      - "27013:27017"
    volumes:
      - ${MTN_DB_PATH}/dbc3:/data/db
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  rsinitiate:
    image: "ateventhorizon/49view-mongo-rsinitiate"
    container_name: "rsinititate-dev"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["sh", "-c", "rsinitiate.sh"]    
