version: "3"
services:
  nginx:
    image: "ateventhorizon/nginx"
    container_name: "main_nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - restful-api
      - portal
    volumes:
      - /sslcerts/fullchain.pem:/etc/nginx/dns-cert.pem
      - /sslcerts/privkey.pem:/etc/nginx/dns-cert-key.pem
  restful-api:
    image: "ateventhorizon/restful-api"
    container_name: "restful-api"
    environment:
      - EH_MONGO_PATH=${EH_MONGO_PATH} 
      - EH_MONGO_DEFAULT_DB=${EH_MONGO_DEFAULT_DB}
      - EH_MONGO_REPLICA_SET_NAME=${EH_MONGO_REPLICA_SET_NAME}
      - EH_MASTER_TOKEN=${EH_MASTER_TOKEN}
      - EH_SEND_GRID_TOKEN=${EH_SEND_GRID_TOKEN}
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  portal:
    image: "eventhorizonprojects/${EH_CLOUD_HOST}"
    container_name: "portal"
  asset_daemon:
    image: "ateventhorizon/asset_daemon"
    container_name: "asset-daemon"
    restart: always
    ports:
      - "27017:27017"
    environment:
      - EH_MONGO_PATH=${EH_MONGO_PATH} 
      - EH_MONGO_DEFAULT_DB=${EH_MONGO_DEFAULT_DB}
      - EH_MONGO_REPLICA_SET_NAME=${EH_MONGO_REPLICA_SET_NAME}
    depends_on:
      - rsinitiate
  mongo1:
    image: "mongo"
    container_name: "mongodb_container1"
    restart: always
    volumes:
      - ${MTN_DB_PATH}/dbc:/data/db
    expose:
      - 27017
    ports:
      - "27011:27017"
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  mongo2:
    image: "mongo"
    container_name: "mongodb_container2"
    restart: always
    expose:
      - 27017
    volumes:
      - ${MTN_DB_PATH}/dbc2:/data/db
    ports:
      - "27012:27017"
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  mongo3:
    image: "mongo"
    container_name: "mongodb_container3"
    restart: always
    expose:
      - 27017
    ports:
      - "27013:27017"
    volumes:
      - ${MTN_DB_PATH}/dbc3:/data/db
    entrypoint: ["/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "${EH_MONGO_REPLICA_SET_NAME}"]
  rsinitiate:
    image: "ateventhorizon/mongo-rsinitiate"
    container_name: "rsinititate"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["sh", "-c", "rsinitiate.sh"]    
